In [94]:
import kagglehub
import pandas as pd
import os
import numpy as np
from sqlalchemy import create_engine,text

In [95]:
# Download latest version
path = kagglehub.dataset_download("hammadansari7/e-commerce-orders-and-customer")

print("Path to dataset files:", path)

Path to dataset files: C:\Users\paul.cavero\.cache\kagglehub\datasets\hammadansari7\e-commerce-orders-and-customer\versions\1

In [96]:
# Inspect files
print(os.listdir(path))

# Read file
df = pd.read_excel(os.path.join(path, "E-Commerce Orders.csv.xlsx"))
print(df.head())

['E-Commerce Orders.csv.xlsx']
     OrderID       Date CustomerID  Product  Quantity  UnitPrice  \
0  ORD200000 2023-01-04     C72649  Monitor         5     570.62
1  ORD200001 2024-08-23     C75739    Phone         2     151.35
2  ORD200002 2024-02-27     C81728   Tablet         5     550.68
3  ORD200003 2023-10-15     C33540    Chair         1     273.19
4  ORD200004 2025-05-08     C81840  Printer         4     626.01

  ShippingAddress PaymentMethod OrderStatus TrackingNumber  ItemsInCart  \
0     928 Main St    Debit Card     Shipped    TRK37947903            7
1     823 Main St        Online     Shipped    TRK91186779            3
2     512 Main St   Credit Card   Cancelled    TRK42903982            8
3     275 Main St    Debit Card    Returned    TRK62788070            5
4     668 Main St        Online   Delivered    TRK29241424            8

  CouponCode ReferralSource  TotalPrice
0     SAVE10      Instagram     2853.10
1     SAVE10       Referral      302.70
2   FREESHIP          Email     2753.40
3     SAVE10       Facebook      273.19
4     SAVE10          Email     2504.04

In [99]:
# Rename columns
df.rename(columns={"OrderID": "order_id", 
                   "Date": "fecha", 
                   "CustomerID": "id_cliente",
                   "Product": "producto",
                   "Quantity": "cantidad",
                   "UnitPrice": "precio_unitario",
                     "ShippingAddress": "direccion_envio",
                        "PaymentMethod": "metodo_pago",
                        "OrderStatus": "estado_pedido",
                        "TrackingNumber": "numero_seguimiento",
                        "ItemsInCart": "articulos_en_carrito",
                        "CouponCode": "codigo_cupon",
                        "ReferralSource": "fuente_referencia",
                        "TotalPrice": "precio_total",
                   }, inplace=True)
print(df.head())

    order_id      fecha id_cliente producto  cantidad  precio_unitario  \
0  ORD200000 2023-01-04     C72649  Monitor         5           570.62
1  ORD200001 2024-08-23     C75739    Phone         2           151.35
2  ORD200002 2024-02-27     C81728   Tablet         5           550.68
3  ORD200003 2023-10-15     C33540    Chair         1           273.19
4  ORD200004 2025-05-08     C81840  Printer         4           626.01

  direccion_envio  metodo_pago estado_pedido numero_seguimiento  \
0     928 Main St   Debit Card       Shipped        TRK37947903
1     823 Main St       Online       Shipped        TRK91186779
2     512 Main St  Credit Card     Cancelled        TRK42903982
3     275 Main St   Debit Card      Returned        TRK62788070
4     668 Main St       Online     Delivered        TRK29241424

   articulos_en_carrito codigo_cupon fuente_referencia  precio_total
0                     7       SAVE10         Instagram       2853.10
1                     3       SAVE10          Referral        302.70
2                     8     FREESHIP             Email       2753.40
3                     5       SAVE10          Facebook        273.19
4                     8       SAVE10             Email       2504.04

In [100]:
# type correctly columns
df["fecha"] = pd.to_datetime(df["fecha"], errors="coerce")
df["cantidad"] = pd.to_numeric(df["cantidad"], errors="coerce")
df["precio_unitario"] = pd.to_numeric(df["precio_unitario"], errors="coerce")
df["precio_total"] = pd.to_numeric(df["precio_total"], errors="coerce")
df["articulos_en_carrito"] = pd.to_numeric(df["articulos_en_carrito"], errors="coerce")
print(df.dtypes)

order_id                           str
fecha                   datetime64[us]
id_cliente                         str
producto                           str
cantidad                         int64
precio_unitario                float64
direccion_envio                    str
metodo_pago                        str
estado_pedido                      str
numero_seguimiento                 str
articulos_en_carrito             int64
codigo_cupon                       str
fuente_referencia                  str
precio_total                   float64
dtype: object

In [101]:
duplicates = df.duplicated().sum()
print(f"Number of duplicate rows: {duplicates}")

Number of duplicate rows: 0

In [102]:
duplicates_by_date = df[df.duplicated(subset=["fecha"], keep=False)]
print(f"Rows with duplicate by fechas: {duplicates_by_date.shape[0]}")

Rows with duplicate by fechas: 880

In [103]:
non_duplicates   = df.drop_duplicates(subset=["fecha","id_cliente"], keep="first")
print(f"Rows without duplicate by fechas and id_cliente: {non_duplicates.shape[0]}")

Rows without duplicate by fechas and id_cliente: 1200

In [104]:
display(non_duplicates.head())

,order_id,fecha,id_cliente,producto,cantidad,precio_unitario,direccion_envio,metodo_pago,estado_pedido,numero_seguimiento,articulos_en_carrito,codigo_cupon,fuente_referencia,precio_total
0,ORD200000,2023-01-04,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10
1,ORD200001,2024-08-23,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70
2,ORD200002,2024-02-27,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40
3,ORD200003,2023-10-15,C33540,Chair,1,273.19,275 Main St,Debit Card,Returned,TRK62788070,5,SAVE10,Facebook,273.19
4,ORD200004,2025-05-08,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04

In [105]:
non_duplicates["count_pagos_by_tipo"] = (
    non_duplicates
    .groupby("metodo_pago")["order_id"]
    .transform("count")
)
display(non_duplicates.head())

,order_id,fecha,id_cliente,producto,cantidad,precio_unitario,direccion_envio,metodo_pago,estado_pedido,numero_seguimiento,articulos_en_carrito,codigo_cupon,fuente_referencia,precio_total,count_pagos_by_tipo
0,ORD200000,2023-01-04,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10,232
1,ORD200001,2024-08-23,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70,258
2,ORD200002,2024-02-27,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40,234
3,ORD200003,2023-10-15,C33540,Chair,1,273.19,275 Main St,Debit Card,Returned,TRK62788070,5,SAVE10,Facebook,273.19,232
4,ORD200004,2025-05-08,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04,258

In [106]:
non_duplicates["descuento"] = np.where(
    (
        (non_duplicates["count_pagos_by_tipo"] < 500) &
        (non_duplicates["metodo_pago"] == "Online")
    ),
    non_duplicates["precio_total"] * 0.10,
    0
)
non_duplicates["final_total"] = non_duplicates["precio_total"] - non_duplicates["descuento"]
display(non_duplicates.head())

,order_id,fecha,id_cliente,producto,cantidad,precio_unitario,direccion_envio,metodo_pago,estado_pedido,numero_seguimiento,articulos_en_carrito,codigo_cupon,fuente_referencia,precio_total,count_pagos_by_tipo,descuento,final_total
0,ORD200000,2023-01-04,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10,232,0.000,2853.100
1,ORD200001,2024-08-23,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70,258,30.270,272.430
2,ORD200002,2024-02-27,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40,234,0.000,2753.400
3,ORD200003,2023-10-15,C33540,Chair,1,273.19,275 Main St,Debit Card,Returned,TRK62788070,5,SAVE10,Facebook,273.19,232,0.000,273.190
4,ORD200004,2025-05-08,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04,258,250.404,2253.636

In [112]:
# conexion
engine = create_engine(
    "postgresql+psycopg2://postgres:admin@localhost:5432/ecomerce"
)

In [108]:
# Query
query = """
SELECT *
FROM fact_ventas;
"""

# Load data into dataframe
df = pd.read_sql(query, engine)

# Show data
print(df.head())

Empty DataFrame
Columns: [sk_venta, order_id, fecha, sk_cliente, sk_producto, cantidad, final_total]
Index: []

In [ ]:
# insert into database from non_duplicates dataframe
non_duplicates.to_sql("ventas", engine, if_exists="replace", index=False)
# read data from database to check if it was inserted correctly
df = pd.read_sql("SELECT * FROM ventas", engine)
print(df.head())

Empty DataFrame
Columns: [sk_venta, order_id, fecha, sk_cliente, sk_producto, cantidad, final_total]
Index: []

In [110]:
with engine.begin() as conn:

    # 1. Insert unique clients into dim_cliente
    conn.execute(text("""
        INSERT INTO dim_cliente (id_cliente)
        SELECT DISTINCT id_cliente
        FROM ventas
        WHERE id_cliente IS NOT NULL
        ON CONFLICT (id_cliente) DO NOTHING;
    """))

    # 2. Insert unique products into dim_producto
    conn.execute(text("""
        INSERT INTO dim_producto (producto)
        SELECT DISTINCT producto
        FROM ventas
        WHERE producto IS NOT NULL
        ON CONFLICT (producto) DO NOTHING;
    """))

    # 3. Insert sales into fact_ventas
    conn.execute(text("""
        INSERT INTO fact_ventas (
            order_id,
            fecha,
            sk_cliente,
            sk_producto,
            cantidad,
            final_total
        )
        SELECT
            v.order_id,
            v.fecha,
            dc.sk_cliente,
            dp.sk_producto,
            v.cantidad,
            v.final_total
        FROM ventas v
        JOIN dim_cliente dc
            ON v.id_cliente = dc.id_cliente
        JOIN dim_producto dp
            ON v.producto = dp.producto
        ON CONFLICT (order_id) DO NOTHING;
    """))

## Total sales by customer

In [115]:
# Query
query = """
SELECT
    dc.id_cliente,
    SUM(f.final_total) AS total_gastado
FROM fact_ventas f
JOIN dim_cliente dc ON f.sk_cliente = dc.sk_cliente
GROUP BY dc.id_cliente
ORDER BY total_gastado DESC;
"""

# Load data into dataframe
df = pd.read_sql(query, engine)

# Show data
print(df.head())

  id_cliente  total_gastado
0     C38840       5384.135
1     C67260       3390.800
2     C13877       3384.900
3     C16775       3353.750
4     C65986       3352.400

## Total sales by product

In [117]:
# Query
query = """
SELECT
    dp.producto,
    SUM(f.final_total) AS total_gastado
FROM fact_ventas f
JOIN dim_producto dp ON f.sk_producto = dp.sk_producto
GROUP BY dp.producto
ORDER BY total_gastado DESC;
"""

# Load data into dataframe
df = pd.read_sql(query, engine)

# Show data
print(df.head())

  producto  total_gastado
0  Printer     191658.760
1    Chair     190185.919
2   Laptop     189089.463
3   Tablet     182241.373
4  Monitor     172127.464

## Sales by day

In [119]:
# Query
query = """
SELECT
	fecha, SUM(final_total) AS total
FROM fact_ventas
GROUP BY fecha
ORDER BY fecha;
"""

# Load data into dataframe
df = pd.read_sql(query, engine)

# Show data
print(df.head())

        fecha    total
0  2023-01-01  1850.88
1  2023-01-02  1323.55
2  2023-01-03   897.70
3  2023-01-04  3629.54
4  2023-01-05  3642.30